[package]
name = "stunclient"
version = "0.1.0"
authors = ["Vitaly _Vi Shukela <vi0oss@gmail.com>"]
edition = "2018"

[dependencies]
stun_codec = "0.1.10"
bytecodec = "0.4.11"
rand = "0.6"

[replace]
"stun_codec:0.1.10" = {path = "/mnt/src/git/stun_codec"}
